export const CLIENT_QUERY_PRODUCT_TOP = "CLIENT_QUERY_PRODUCT_TOP";
export const CLIENT_QUERY_PRODUCT_RANDOM = "CLIENT_QUERY_PRODUCT_RANDOM";
export const CLIENT_QUERY_TERMS_OF_SERVICE = "CLIENT_QUERY_TERMS_OF_SERVICE";
export const CLIENT_QUERY_RETURN_POLICY = "CLIENT_QUERY_RETURN_POLICY";

export const ADMIN_QUERY_ALL_USER = "ADMIN_QUERY_ALL_USER";
export const ADMIN_QUERY_INSERT_PRODUCT = "ADMIN_QUERY_INSERT_PRODUCT";
export const ADMIN_QUERY_SELECT_PRODUCT = "ADMIN_QUERY_SELECT_PRODUCT";
